post:
  tags:
    - profiles
  operationId: createProfile
  description: Create a profile for a firebase authenticated user
  requestBody:
    content:
      application/json:
        schema:
          type: object
          properties:
            firebaseUserUID:
              type: string
              example: '1'
              required: true
            profile:
              $ref: '../../schemas/profile.yml'
  responses:
    '200':
      description: Success
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: number
                example: 200
              message:
                type: string
                example: ''
              data:
                type: object
                properties:
                  profile:
                    $ref: '../../schemas/profile.yml'
    '404':
      description: Firebase User Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: number
                example: 404
              message:
                type: string
                example: Firebase User with id of 'foo' does not exist
    '422':
      description: Malformed User Creation Error
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: number
                example: 404
              message:
                type: string
                example: Missing 'displayName' property
