openapi: 3.0.0

servers:
  - description: localhost
    url: http://localhost:5001/hangzone-494fc/us-central1
  - description: Production
    url: https://hangzone-494fc/us-central1

info:
  description: Hangzone Firestore JSON API
  title: Hangzone Firestore JSON API
  contact:
    email: burdick.aaron@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: profiles
    description: Having to do with profiles
  - name: friends
    description: Having to do with friends

paths:
  /api/profiles:
    $ref: './paths/api/profiles/collection.yml'
  /api/profiles/friends:
    $ref: './paths/api/profiles/friends.yml'
