openapi: 3.0.0

servers:
  - description: localhost
    url: http://localhost:5001/hangzone-494fc/us-central1
  - description: Production
    url: https://hangzone-494fc/us-central1

info:
  description: Hangzone Firestore JSON API
  title: Hangzone Firestore JSON API
  contact:
    email: burdick.aaron@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: attribute answers
    description: Also referred to as "tags". Belong to attribute questions.

paths:
  /api/profiles:
    $ref: './paths/api/profiles.yml'
